name: Run Unit Tests

on:
  push:
    branches:
      - main      # Run tests when pushing to the main branch
  pull_request:
    branches:
      - main      # Run tests when creating a pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu machine

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GCC
      run: |
        sudo apt update
        sudo apt install -y build-essential gcc make

    - name: Compile and run tests
      run: |
        cd tests
        make            # Compile the tests
        make run_tests  # Run the tests

    - name: Clean up
      run: make clean   # Clean up the build files
