name: Run Unit Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GCC
        run: sudo apt-get install gcc

      - name: Compile and run tests
        run: |
          cd tests
          make clean  # Clean any old compiled files
          make        # Compile the tests
          make run_tests  # Run the tests
