name: XOR Encryption Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCC
      run: sudo apt-get install build-essential

    - name: Compile and run test
      run: |
        make clean
        make
        ./test_xor
