name: C Program Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up GCC (C compiler)
      - name: Set up GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Change to the tests directory and compile the tests
      - name: Compile tests
        run: |
          cd tests
          make

      # Run the unit tests
      - name: Run unit tests
        run: |
          cd tests
          make run_tests

      # Clean up (optional)
      - name: Clean up
        run: |
          cd tests
          make clean
